//Navbar list Data
export const navbar = [
  "Hello Select your Address",
  "Hello,Sign in Account & lists",
  "Return & orders",
];

//Navigation Item List
export const nav = [
  "All",
  "Sell",
  "Best Sellers",
  "Today's Deal",
  "Mobiles",
  "CustomerService",
  "Electronics",
  "Books",
  "Fashion",
  "Home & Kitchen",
  "Prime",
  "Coupnes",
  "Computers",
];

//Box1 Items
export const box = [
  {
    Title: "Extra happiness days",
    Image: "/images/a1.jpg",
    About: "See All Offers",
  },
  {
    Title: "Up to 60% off | Double door refrigerators",
    Image: "/images/a2.jpg",
    About: "See All Offers",
  },
  {
    Title: "Coupon Carnival | Special offers for you",
    Image: "/images/b3.jpg",
    About: "See All Offers",
  },
  {
    Title: "Earn up to ₹7,500 on cashback",
    Image: "/images/img17.jpg",
    About: "See All Offers",
  },
];

//Box2 Items
export const a = [
  {
    Heading: "Unlock savings on home, kitchen & more",
    img1: "/images/img1.jpg",
    About1: "Decor",

    img2: "/images/img2.jpg",
    About2: "Cooking",

    img3: "/images/img3.jpg",
    About3: "Sports",

    img4: "/images/img4.jpg",
    About4: "Home",
    Link: "See all offers",
  },
  {
    Heading: "Up to 70% off | Upgrade to latest appliances",
    img1: "/images/img5.jpg",
    About1: "Front Loads",

    img2: "/images/img6.jpg",
    About2: "Refrigertator",

    img3: "/images/img7.jpg",
    About3: "Inverter Acs",

    img4: "/images/img8.jpg",
    About4: "Microwaves",
    Link: "See all offers",
  },
  {
    Heading: "Up to 70% off | Upgrade to latest appliances",
    img1: "/images/img9.jpg",
    About1: "Refrigertator",

    img2: "/images/img10.jpg",
    About2: "kitchen acc",

    img3: "/images/img11.jpg",
    About3: "Essentials",

    img4: "/images/img12.jpg",
    About4: "clothing",
    Link: "See all offers",
  },
  {
    Heading: "Deals on beauty | ​Up to 70% off",
    img1: "/images/img13.jpg",
    About1: "Skincare",

    img2: "/images/img14.jpg",
    About2: "Haircare",

    img3: "/images/img15.jpg",
    About3: "Makeup",

    img4: "/images/img16.jpg",
    About4: "Bath shower",
    Link: "See all offers",
  },
];

// Register Page Data
export const register = [
  {
    name: "firstName",
    type: "text",
    place: "first name",
    size: "28",
  },
  { name: "lastName", type: "text", place: "Last name", size: "28" },
  {
    name: "Email",
    type: "Email",
    place: "Enter Email",
    size: "27",
  },
  {
    name: "Image",
    type: "file",
    place: "Select Image",
    size: "28",
  },
  {
    name: "Password",
    type: "Password",
    place: "Password",
    size: "28",
    padding: "24px",
  },
];

// ShoppingCartData
export const cartData = [
  {
    id:1,
    img: "/images/f2.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 17",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30.5D x 30.5W x 30.5H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'10 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'Wooden Square Table For Home And Office Decoration Made With Durable Wood',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',
    
    ProductDimension:'ProductDimensions',
    ProductDimensions:'30.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'800gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM412'

  },
  {
    id:2,
    img: "/images/f3.jpg",
    item: "UHUD CRAFTS Beautiful Antique Wooden Fold-able Side Table/End Table/Plant Stand/Stool Living Room Kids Play Furniture Table Round Shape",
    Deal: "DEAL OF THE DAY",
    Price: "559",
    MRP: "MRP 1299.00 (20% off)",
    Delivery: "Get it by Monday, November 27",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30D x 30W x 39H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'7 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'An ideal gift for a housewarming, wedding,Christmas, Diwali, birthday or anniversary parties , Stool can be used as an end table, chair side table,',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',

    ProductDimension:'ProductDimensions',
    ProductDimensions:'0.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'80gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM4100'
  },
  {
    id:3,
    img: "/images/f11.jpg",
    item: "VDIX Hand-Crafted Folding Side Stool for Living Room and Office | Small Side Table for lamp, Books, Flower Pot or vase, showpieces",
    Deal: "DEAL OF THE DAY",
    Price: "1059",
    MRP: "MRP 1299.00 (20% off)",
    Delivery: "Get it by Monday, November 21",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30D x 30W x 39H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'7 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'An ideal gift for a housewarming, wedding,Christmas, Diwali, birthday or anniversary parties , Stool can be used as an end table, chair side table,',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',

    ProductDimension:'ProductDimensions',
    ProductDimensions:'30.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'800gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM412'
  },
  
  {
    id:4,
    img: "/images/f7.jpg",
    item: "Ultimate twist Beautiful Wooden Folding Stool Foldable Stool for Office, Kitchen & Home Décor Wooden Folding Table (12INCH)",
    Deal: "DEAL OF THE DAY",
    Price: "1459",
    MRP: "MRP 1399.00 (25% off)",
    Delivery: "Get it by Monday, November 26",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30D x 30W x 39H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'7 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'An ideal gift for a housewarming, wedding,Christmas, Diwali, birthday or anniversary parties , Stool can be used as an end table, chair side table,',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',

    ProductDimension:'ProductDimensions',
    ProductDimensions:'30.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'800gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM412'
  },
  {
    id:5,
    img: "/images/f8.jpg",
    item: "ART AND CRAFT INDIA Wooden Round Folding Stool for Living Room| Side Stool| Table for Bedroom| Stool for- Dressing Table, Bedside, Home, Office, Balcony (Natural Brown)",
    Deal: "DEAL OF THE DAY",
    Price: "2559",
    MRP: "MRP 1299.00 (20% off)",
    Delivery: "Get it by Monday, November 22",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30D x 30W x 39H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'7 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'An ideal gift for a housewarming, wedding,Christmas, Diwali, birthday or anniversary parties , Stool can be used as an end table, chair side table,',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',

    ProductDimension:'ProductDimensions',
    ProductDimensions:'30.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'800gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM412'
  },
   {
    id:6,
    img: "/images/f10.jpg",
    item: "M.M HANDICRAFTS Wooden Folding Stool Living Room Side Table/Vases Holder//Foldable Adjustable Side Table/Coffee Table/Plant Stand/Gift Table/Stool 12Inch (Brown)",
    Deal: "DEAL OF THE DAY",
    Price: "659",
    MRP: "MRP 1299.00 (20% off)",
    Delivery: "Get it by Monday, November 29",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days ",
    Brand:'Brand: Generic',
    
    Product :'Product dimensions :30D x 30W x 39H Centimeters',
    Colour:	'Color : Brown',
    Shape	:'Shape  : Square',
    Del:'Free Delivery',
    Replace:'7 days Replacement Only',
    Delivered:'Amazone Delivered',
    About:'An ideal gift for a housewarming, wedding,Christmas, Diwali, birthday or anniversary parties , Stool can be used as an end table, chair side table,',
    compare:'Compare with similar items',
    stock:'In Stock',
    Sold:'Sold by SURPRISE INTERIORS and Delivered by Amazon.',
    button:'Add to Cart',
    buy:'Buy Now',
    wishlist:'Add to Wish List',

    ProductDimension:'ProductDimensions',
    ProductDimensions:'30.5D x 30.5W x 30.5H Centimeters',
    Color:'Colour',
    color:'white',
    Shape:'Shape',
    shape:'Square',
    Brand:'Brand',
    Brand1:'Generic',
    Size :'Size',
    Size1:'Medium',
    ItemWeight:'Item Weight',
    ItemWeight1:'800gm',
    Packer:'Packer',
    Packer1:'	Noor Enterprises',
    Manufacturer:'Manufacturer',
    Manufacturer1:'	Noor Enterprises, Noor Enterprises',
    TopMaterialType:'TopMaterialType',
    TopMaterialType1:'Wood',
    ASIN:'ASIN',
    ASIN1:'B09YVBM412'
  },
];

// Today Deal 
export const Deals = [
  {
    image: "/images/d1.jpg",
    off: "Up to 69% off",
    deal: "Deal of the day",
    offers: "Offers on Wireless Accessories",
  },
  {
    image: "/images/d2.jpg",
    off: "Up to 28% off",
    deal: "Deal of the day",
    offers: "DJI Gimbals from INR 7999 - upto to 6M NCEMI",
  },
  {
    image: "/images/d3.jpg",
    off: "Up to 70% off",
    deal: "Deal of the day",
    offers:
      "Newly Launched Noise Two On-Ear Headphones with 50 Hours Playtime ,",
  },
  {
    image: "/images/d4.jpg",
    off: "Up to 22% off",
    deal: "Deal of the day",
    offers: "Chocolates And Gifiting",
  },
  {
    image: "/images/d5.jpg",
    off: "Up to 50% off",
    deal: "Deal of the day",
    offers: "NIKE, ASICS ,New Balance Upto 70% Off",
  },
];

//Computer Accessories
export const accessories = [
  {
    img: "/images/e1.jpg",
  },
  {
    img: "/images/e2.jpg",
  },
  {
    img: "/images/e3.jpg",
  },
  {
    img: "/images/e4.jpg",
  },
  {
    img: "/images/e5.jpg",
  },
  {
    img: "/images/e6.jpg",
  },
  {
    img: "/images/e7.jpg",
  },
];

export const ProductData = [
  {
    id:1,
    img: "/images/f10.jpg",
    item: "VDIX Hand-Crafted Wood Folding Small Side Stool Table for Lamp, Books, Flower Pot (Brown)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
  {
    id:1,
    img: "/images/f3.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
  {
    id:1,
    img: "/images/f8.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
  {
    id:1,
    img: "/images/g6.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
  {
    id:1,
    img: "/images/f11.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
   
  {
    id:1,
    img: "/images/f2.jpg",
    item: "Wooden Folding Square Side Stool Used for Home and Office Decor (Noor Stocks)",
    Deal: "DEAL OF THE DAY",
    Price: "663",
    MRP: "MRP 1499.00 (50% off)",
    Delivery: "Get it by Monday, November 7",
    freeDelvivery: "FREE Delivery over ₹499.",
    Amazone: "Fulfilled by Amazon",
    EndingDate: "Ends in 17 days "
  },
]